#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect below requirements
# 1. Install Nginx listening on port 80
# 2. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# You cannot use systemctl for restarting nginx

# Install Nginx
sudo apt-get update -y && sudo apt-get install -y nginx

# Start Nginx
sudo service nginx restart

# Cehck if Nginx is running
if ! pgrep -x "nginx" > /dev/null; then
	echo "Nginx failed to start" >&2
	exit 1
fi

# Configure default Nginx page
sudo echo "Hello World!" > /var/www/html/index.html

# Test Nginx
curl --silent http://localhost | grep -Fq 'Hello World!'

# Check if curl output contains "Hello World!"
if [ $? -ne 0 ]; then  # if the status code  was not 0, an error occurred
    echo "Failed to configure the default Nginx page" >&2
    exit 1
else
    echo "Successfully configured the default Nginx page"
fi

exit 0
