#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

# Install Nginx
sudo apt-get update && sudo apt-get install -y nginx

# Restart Nginx
sudo service nginx restart

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give user ownership to website files for ease of editing
sudo chown -R "$USER":"$USER" /var/www/html/*
sudo chmod -R 755 /var/www

# Configure redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
