#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

# Install Nginx
sudo apt-get update && sudo apt-get install -y nginx

# Restart Nginx
sudo service nginx restart

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give user ownership to website files for ease of editing
sudo chown -R "$USER":"$USER" /var/www/html/*
sudo chmod -R 755 /var/www

# Configure redirection
new_string="server_name _;\n\tlocation /redirect_me {\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;\n\t}"
# finds s/server_name _; in default configuration and replace it with new string
sudo sed -i "s#server_name _;#$new_string#"  /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
