#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# install and update Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# crete error 404 file and put desired message in it
echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html

# create 404 directive inside stes-enabled/default file
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
