#!/usr/bin/env bash
# This scrit displays "Best School" 10 times
# for 9th iteration, displays "Hi" additionally

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
