#!/usr/bin/env bash
# This script diplays the time for 12 hours and 59 minutes

hour=1
while [ $hour -le 12 ]
do
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	echo "Hour: $hour"
	((hour++))
done
