#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

# Requirements:

# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Write a Bash script that configures the container to fit the above requirements

sed -i 's/user\s*nginx;/user nginx nginx;/' /etc/nginx/nginx.conf

# Restart Nginx
nginx -s reload

# Verify Nginx is running as nginx user
ps auxff | grep ngin[x]
