#!/usr/bin/env bash
# script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
if [ -f ~/.ssh/school ]; then
	ssh  -i ~/.ssh/school ubuntu@530453-web-01
fi
